import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransistion from "@/components/StairTransistion";

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono',
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://raw.githubusercontent.com/Pavulururohith/Photos/main/Frame%20209.svg" type="image/svg+xml" />
      </head>
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransistion />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
